language: node_js
node_js:
- '0.10'
addons:
  code_climate:
    repo_token: c8d5de4eefe8739b3fc508c5194e8258964c8222a3fffe0b73b9c00652d8c2c9
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key:
    secure: HIAc1J0ybDbsyiy7hbQu2+yWPWRJj1dlBeWAloDpSyVI93+3uQXsvFz1tFwLK+QRC4y3ymdTYFTcvyVFeFy76Incaprir4Y/A2N0U3ttKgCxWAAZ8OY6TTQGgAvGaPJxrhYxzYKmV4dpx3l2WzsdgPxWqA+etlFjm/xXc8w3fF0=
  on:
    tags: true
    repo: simbo/metalsmith-robotskirt
    all_branches: true
after_script:
- npm run cover
- cat coverage/lcov.info | ./node_modules/.bin/codeclimate
