language: node_js
node_js:
- '0.10'
addons:
  code_climate:
    repo_token: c8d5de4eefe8739b3fc508c5194e8258964c8222a3fffe0b73b9c00652d8c2c9
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key:
    secure: aLPRbODhWHA4P9OTVdJyfXXPGHYBeffmu1bXT4rmMpaLvmbpaBoUKy3/+nh6ft5ENYQIazTXxwKa1GhS2tv1fRZXELNZkStt4r42jaCRHbi0hNImQbiIR7Bs3uodRsXU4Gmchy9BdeDLDIZwchTiPcHElCI3SzY6rrpvsqxMy5I=
  on:
    tags: true
    repo: simbo/metalsmith-robotskirt
    all_branches: true
after_script:
- npm run cover
- cat coverage/lcov.info | ./node_modules/.bin/codeclimate
